### ISSUE TITLE
Solucionar ausência de dados na impressão de gratificações de magistério

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/SisWeb#20]
Solicitação enviada pela CEATS em 29/07/2020, para o e-mail institucional de @rmadev-master .

**Ações necessárias**

- [x] Realizar backup da produção;
- [x] Restaurar na base de testes;
- [x] Atualizar acessos;
- [x] Realizar manutenção;
- [x] Publicar resultados.

**Comment by rmadev-master** [comment]
- [ ] Realizar backup da produção;
- [ ] Restaurar na base de testes;
- [ ] Atualizar acessos;
- [ ] Realizar manutenção;
- [ ] Publicar resultados.

**Comment by rafaelmassuncao** [comment]
Em andamento: backup

**Comment by rafaelmassuncao** [comment]
Em andamento: restaurando bases de dados

**Comment by rafaelmassuncao** [comment]
Os dados haviam sido expirados, erroneamente.
