### ISSUE TITLE
Ativar dados de GRM para professora

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/SisWeb#23]
Solicitada para o e-mail institucional do colaborador @rmadev-master , aos 06/08/2020.

**Ações:**

- [x] Verificação e backup de dados em andamento
- [x] Recepcionando backup de dados
- [x] Realizando manutenção
- [x] Resultados publicados

**Comment by rmadev-master** [comment]
Verificação e backup de dados em andamento.

**Comment by rafaelmassuncao** [comment]
Concluído.
